
  name: dnsfw-snap-dev
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Bind DNS server plus config files for RPZ support
  description: |
    Protect your network's users by using a DNS Firewall.  

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    bind9:
      # See 'snapcraft plugins'
      stage-packages: bind9
      
  
